### ISSUE TITLE
Good job

### ISSUE THREAD

**Issue by journeyly** [royeo/weapp-store#1]
Hi, Royeo,
You have done a good job.
I would like to say thank you for your sharing.
Maybe you can add more functions to this project, such as:

1, When showing a store, you can give more information, like description, comments, phone number, open/close time and so on.
2, Add a navigation for these stores so that we can easily go there.
3, Make a classification for these stores like some open for 24 hours, some are very small, some are with a good reputation.

**Comment by royeo** [comment]
The functions you mentioned are all great, I also considered adding these functions before. 

But collecting store information is a huge task, and this information is so valuable that no company willing to open these API to get store information. So I decided not to show the details of the store.

I also plan to add navigation in the next version, thank you so much for your suggestion.
